"""Pydantic v2 request schemas — all inputs validated and sanitised here."""
from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


def _strip_dangerous_content(text: str) -> str:
    """Remove HTML tags and script-like patterns from user input."""
    # Remove HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Remove javascript: / data: URIs
    text = re.sub(r"(?i)(javascript|data|vbscript):", "", text)
    # Collapse whitespace
    text = " ".join(text.split())
    return text.strip()


class ChatRequest(BaseModel):
    """Request body for POST /api/v1/chat."""

    model_config = ConfigDict(str_strip_whitespace=True)

    session_id: str = Field(
        ...,
        min_length=36,
        max_length=36,
        pattern=r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
        description="UUID4 session identifier generated by the client",
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="User's question (max 500 characters)",
    )
    language: Literal["en", "hi"] = Field(
        default="en",
        description="Response language: 'en' for English, 'hi' for Hindi",
    )

    @field_validator("message")
    @classmethod
    def sanitise_message(cls, v: str) -> str:
        cleaned = _strip_dangerous_content(v)
        if not cleaned:
            raise ValueError("Message cannot be empty after sanitisation")
        return cleaned


class FeedbackRequest(BaseModel):
    """Request body for POST /api/v1/feedback."""

    model_config = ConfigDict(str_strip_whitespace=True)

    session_id: str = Field(
        ...,
        min_length=36,
        max_length=36,
        pattern=r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    message_id: str = Field(
        ...,
        min_length=1,
        max_length=64,
    )
    rating: Literal[1, -1] = Field(
        ...,
        description="1 = helpful, -1 = not helpful",
    )
    language: Literal["en", "hi"] = Field(default="en")
